dist: xenial
language: python
python:
    - "3.6"
    - "3.7"
services:
    - mysql

script:
    - py.test tests/
    - bash tests/test.bash

install:
    - pip install -r requirements.txt -e .

notification:
    - email: false
