language: python
python:
    - "2.7"
    - "3.6"
services:
    - mysql

script:
    - py.test tests/
    - bash tests/test.bash

install:
    - pip install -r requirements.txt -e .

notification:
    - email: false
