name: Demultiplexing CI

on: ["push", "pull_request"]

jobs:

  tests-coverage:

    runs-on: ubuntu-latest

    steps:

    # Check out Demultiplexing code
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.4

    - name: Demultiplexing dependencies
      run: |
        poetry install

    - name: Coveralls Dependencies
      run: |
        pip install pytest-cov coveralls

    - name: Test with pytest & Coveralls
      run: |
        pytest --cov=demux/
        bash tests/test.bash
        coveralls
      env:
        GITHUB: 1
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}