---
name: Demultiplex installation tests

"on": ["pull_request"]

jobs:
    installations:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.7]

        steps:
            - name: Check out git repository
              uses: actions/checkout@v2

            # Set up python
            - name: Set up Python ${{matrix.python-version}}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{matrix.python-version}}

            - name: Install pip
              # Make sure that we have correct python version and pip version
              # For details see .github/workflows/server_info.md
              run: |
                  python -m pip install --upgrade pip==18.1
                  echo $PYTHON_VERSION
                  pip --version
              env:
                  PYTHON_VERSION: ${{matrix.python-version}}

            - name: Production Dependencies
              run: |
                  pip install micropipenv[toml]
                  micropipenv requirements --method poetry > requirements.txt
                  pip install -r requirements.txt
                  pip check
