name: Demultiplexing CI

on: ["push", "pull_request"]

jobs:

  tests-coverage:

    runs-on: ubuntu-latest

    steps:

    # Check out Demultiplexing code
    - uses: actions/checkout@v2

    # Set up python
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Demultiplexing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements.txt

    - name: Coveralls Dependencies
      run: |
        pip install pytest-cov coveralls

    - name: Test with pytest & Coveralls
      run: |
        pytest --cov=demultiplexing/
        bash tests/test.bash
        coveralls
      env:
        GITHUB: 1
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}